### ISSUE TITLE
[ERROR] System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0...

### ISSUE THREAD

**Issue by stanislav-poliakov** [getsentry/raven-csharp#186]
```c#
[ERROR] System.IO.FileLoadException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The file cannot be accessed by the system. (Exception from HRESULT: 0x80070780)
File name: 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at SharpRaven.Data.SentryUserFactory.Create()
   at SharpRaven.RavenClient.PreparePacket(JsonPacket packet)
   at SharpRaven.Data.Requester..ctor(JsonPacket packet, RavenClient ravenClient)
   at SharpRaven.RavenClient.<SendAsync>d__f.MoveNext()
```

```
=== Pre-bind state information ===
LOG: DisplayName = Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///{cut}
LOG: Initial PrivatePath = NULL
Calling assembly : SharpRaven, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: {cut}.vshost.exe.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Redirect found in application configuration file: 4.0.0.0 redirected to 4.0.0.0.
LOG: Post-policy reference: Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
```

**Comment by stanislav-poliakov** [comment]
And raven client never capture event, because can't load some assemblies by permissions

**Comment by asbjornu** [comment]
I've never seen this before. The `Microsoft.CSharp` assembly is used to handle language features such as the `dynamic` keyword. What .NET version are you running on and are you hosting this in a particularly strict environment where certain forms of assembly loading is prohibited?

**Comment by stanislav-poliakov** [comment]
Hmm, in any case it was only on my dev pc (I've tried to understand why it happen).
My solution in own code I've call smth from required library (to call some cctor and load assembly);
I guess some logged events happen in strict context, but I have no idea how to fix (assemblies are located in correct folders, .net repair done etc).
```
```
but currently in our Outlook Add-ins we occurs a little bit different issue:
```
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
  Source=SharpRaven
  StackTrace:
   at SharpRaven.RavenClient.<CaptureAsync>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at SharpRaven.RavenClient.CaptureAsync(SentryEvent event)
   at CoreData.Common.Logging.Sentry.SentryAppender.CaptureEvent(SentryEvent sentryEvent, ErrorLevel errorLevel, Func`2 formatFunc) in C:\outlook-plugin\client-common\Common\CoreData.Common\Logging\Sentry\SentryAppender.cs:line 174
``` 
in my app.config I've found:
```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```
NuGet package is Newtown.Json - 9.0.1

**Comment by asbjornu** [comment]
Hm, that's strange. From what I know, JSON.NET v9 should be compatible with v6 and so your assembly redirect should work.

**Comment by mklingen** [comment]
Same problem, Json.net v9 unable to compile against sharpraven

**Comment by mklingen** [comment]
modifying `app.config` fixed the issue.

**Comment by stanislav-poliakov** [comment]
How did you change `app.config`?

**Comment by mklingen** [comment]
You can redirect the `.dll` that's being loaded at runtime like so:

```
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

**Comment by lujvari** [comment]
I also have problem with missing Newtonsoft assembly:
 Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

But i already use higher version that should be compatible:
`<runtime>`
`<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">`
`<dependentAssembly>`
    `<assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />`
        `<bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />`
`</dependentAssembly>`
`</assemblyBinding>`
`</runtime>`

**Comment by asbjornu** [comment]
If you think updating to a newer version of `Newtonsoft.Json` might help, I'd happily accept a pull request doing just that.

**Comment by asbjornu** [comment]
Is this still a problem in [verskion `2.3.2`](https://www.nuget.org/packages/SharpRaven/2.3.2)?

**Comment by LoveDuckie** [comment]
I have a feeling that it might be, although my problem could be unrelated. When I have call backs assigned to AppDomain.Current.FirstChanceException, it gets stuck in a infinite loop because it complains about it not finding a "id" attribute. The exception is throw from somewhere in Newtonsoft.Json. I am not sure if this is related to inconsistent version references. I am using version 10.0.0

**Comment by bruno-garcia** [comment]
We've been working on a new SDK and it would be great to get it tested for this issue.
The code is hosted on GitHub on this repository: https://github.com/getsentry/sentry-dotnet/
and it's published to NuGet as [Sentry](https://www.nuget.org/packages/Sentry)

It targets .NET Standard 2.0 which means supports:
.NET Framework 4.6.2, Mono 5.4 and .NET Core 2.0.

**Comment by LoveDuckie** [comment]
@bruno-garcia cool, I'll give it a look. thanks.

**Comment by bruno-garcia** [comment]
Closing due to inactivity - no reports once 2.3.2 was released
