### ISSUE TITLE
System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.

### ISSUE THREAD

**Issue by awesomehimanshu** [getsentry/raven-csharp#203]
**[ERROR] System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.**
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at SharpRaven.Data.Requester.Request() in c:\BuildAgent\work\6ff01e7f375f2953\src\app\SharpRaven\Data\Requester.cs:line 133
   at SharpRaven.RavenClient.Send(JsonPacket packet) in c:\BuildAgent\work\6ff01e7f375f2953\src\app\SharpRaven\RavenClient.cs:line 362

**More error**

Request body (raw):
[ERROR] [ERROR] [ERROR] Accept: application/json
System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at SharpRaven.Data.Requester.Request() in c:\BuildAgent\work\6ff01e7f375f2953\src\app\SharpRaven\Data\Requester.cs:line 133
   at SharpRaven.RavenClient.Send(JsonPacket packet) in c:\BuildAgent\work\6ff01e7f375f2953\src\app\SharpRaven\RavenClient.cs:line 362

.NET : 4.0

**Comment by awesomehimanshu** [comment]
Can solve by .NET application it self .

WebRequest.DefaultWebProxy.Credentials = CredentialCache.DefaultNetworkCredentials;

or 

 WebRequest.DefaultWebProxy.Credentials = new NetworkCredential("usename", "password");
